insert into public.showroom_stock (showroom, product_id, product_title, quantity) values
  ('gent', 'sunspa-filter-groot', 'Sunspa Filter groot', 11),
  ('gent', 'filterset-zwemspa', 'Filterset zwemspa', 1),
  ('gent', 'sunspa-filter-klein', 'Sunspa Filter klein', 24),
  ('gent', 'filter-explore-san-marino-new-york', 'Filter Explore | san marino | New york', 1),
  ('gent', 'fox-spa-filter', 'Fox spa filter', 2),
  ('gent', 'melpool-chloortabletten-90-20-1kg', 'Melpool Chloortabletten 90/20', 32),
  ('gent', 'melpool-chloorgranulaat-55-g-1kg', 'Melpool Chloorgranulaat 55/G', 31),
  ('gent', 'melpool-ph-plus', 'Melpool pH +', 12),
  ('gent', 'melpool-ph-min', 'Melpool pH -', 11),
  ('gent', 'spa-line-metal-clean', 'Spa Line Spa Metal Clean', 7),
  ('gent', 'spa-line-tube-clean', 'Spa Line Spa Tube Clean', 10),
  ('gent', 'renew', 'Renew', 9),
  ('gent', 'insparation-wellness-geurtjes', 'Wellness - Eucalyptus', 11),
  ('gent', 'spa-line-foam-down', 'Spa Line Spa Foam Down', 8),
  ('gent', 'spa-line-citrus-clean', 'Spa Line Citrus Clean', 1),
  ('gent', 'spa-line-defense', 'Spa Line Spa Defense', 13),
  ('gent', 'spa-line-cover-shine', 'Spa Line Spa Cover Shine', 6),
  ('gent', 'leisure-time-filter-clean', 'Leisure Time Filter Clean', 12),
  ('gent', 'melpool-ta-alkaliteit', 'Melpool TA + Alkaliteit increaser', 10),
  ('gent', 'aquacheck-teststrips-ph-chloor', 'Aquacheck Teststrips pH & Chloor', 18),
  ('gent', 'estelle-filter-cleaner', 'Estelle filter cleaner', 2),
  ('gent', 'drijvende-bartafel', 'Drijvende bartafel', 3),
  ('gent', 'halu-hoofdsteun', 'HaLu hoofdsteun', 12),
  ('gent', 'aquafinesse-pakket', 'Aquafinesse pakket', 2),
  ('gent', 'coverlift-beugel', 'Coverlift beugel', 3),
  ('gent', 'chloordrijver', 'Chloordrijver', 3),
  ('gent', 'spa-line-bright', 'Spa Line Spa Line Bright', 4)
on conflict (showroom, product_id) do update set
  product_title = excluded.product_title,
  quantity = excluded.quantity,
  updated_at = now();
